

describe('Login page', () => {
  before(() => {
    cy.visit('http://localhost:3000/')
  })
  it('Login demo', () => {
    cy.get('.login__demo').click()
  }) 
  it('Sidebar', () => {
    cy.get('[href="/rooms/mKBvfaPplFrmLToewnYC"] > .sidebarChat').click()
      .should('be.visible')
    cy.get('[href="/rooms/vtOl6nBVlIrnINyeYREY"] > .sidebarChat').click()
      .should('be.visible')
    cy.get('[href="/rooms/Lx3t1vI4O5tdriHWm5YH"] > .sidebarChat').click()
      .should('have.css', 'font-size')
    cy.get('h3')
    cy.contains('Family')
  })
    it('Chat', () => {
    cy.get('form > input')
      .click()
      .type("Hello Test{enter}")
    cy.get('[href="/rooms/Lx3t1vI4O5tdriHWm5YH"] > .sidebarChat > .sidebarChat__info > p').contains('Hello Test').should('exist')
    cy.get(':nth-last-child(1) > .chat__message > .MuiSvgIcon-root')
      .click()
      .wait(100)
    cy.contains('El mensaje ha sido eliminado')
    cy.get('.chat__footer > .MuiButtonBase-root').click()
      .wait(100)
    cy.get('[aria-label="Smileys & People"] > .emoji-mart-category-list > :nth-child(2) > .emoji-mart-emoji > span').click()
    cy.get('form > input')
      .type('{enter}')
    cy.get(':nth-last-child(1) > .chat__message')
      .should('have.class', 'chat__message chat__receiver')
    cy.get('.styles_button__3Vugn').click()
    cy.get('.tooltip')
      .should('be.visible')
    cy.contains('Keep holding the button to send a message')
    cy.get('.modal > .MuiButtonBase-root').click()
    cy.get('.uploadImage > p')
      .should('be.visible')
    cy.contains('Upload Files')
    cy.get('.modal > .MuiButtonBase-root').click()
  })
  it('Video', () => {
    cy.get('a > .MuiButtonBase-root').click()
      .should('exist')
    cy.get('.recordVideo__buttonOpen').click()
    cy.get('.recordVideo__buttonStart > div').click()
    cy.get('.recordVideo__buttonClose').click()
    cy.get('.recordVideo__linkCamera').click()
    cy.get('.home')
      .should('exist')
  })

})